name: Update Notion to Supabase

on:
    schedule:
    # Planifie l'exécution du script tous les jours à 8h et 19h
        - cron: '0 8,19 * * *'

jobs:
    update:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                  python-version: '3.x'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Run update script
              env:
                  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
                  SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
                  NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
                  NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
              run: |
                python api/update_users.py